adbc23:
  c_labels: {'A':'A: Plausible','B':'B: Less plausible, attraction','C':'C: Implausible, no attraction'}
  c_palette: ['black','red','blue']
  title: 'Aurnhammer et al. (2023)'
  x_lim: 21
  y_lim: 0.2

adbc23_short:
  c_labels: {'A':'A: Plausible','B':'B: Less plausible, attraction','C':'C: Implausible, no attraction'}
  c_palette: ['black','red','blue']
  title: 'Aurnhammer et al. (2023) short'
  x_lim: 21
  y_lim: 0.2